### ISSUE TITLE
Set Up Your Kanban Board

### ISSUE THREAD

**Issue by PierreBarba** [luigirazum/mv-pokeapp#21]
# Hi ✌🏽  reviewer for this activity my colleagues and I, we made the configuration of the Kanban Board, all suggestions are welcome, have a great day 

## We are three in the Team
@cilfonegabriel 
@luigirazum 
@PierreBarba 

## link to the repository
> https://github.com/luigirazum/mv-pokeapp

## workflow

- create the repository
- We follow the steps to copy the project table
- We follow the steps to download the cards with the project activities
- we assign the activities to each participant
- we review details.

**Comment by Reem-lab** [comment]
# Hi Team, 👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🔥🔥💯💯🚀🚀
<img src="https://media1.giphy.com/media/1O1UUSESiuGSi1VdT6/giphy.gif"/>
## Highlights
- Great working on set up the kanban board💯🚀
- Great job working on the assigning the tasks 💯🚀

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by luigirazum** [comment]
Thanks @Reem-lab for your feedback.
We are moving forward the next activities then.

Cheers,
PokeApp Team 👋
